--
-- Script was generated by Devart dbForge Studio 2022 for SQL Server, Version 6.3.9.0
-- Product home page: http://www.devart.com/dbforge/sql/studio
-- Script date 19/01/2023 4:13:05 pm
-- Server version: 12.0.2000.8
--

SET DATEFORMAT ymd
SET ARITHABORT, ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER, ANSI_NULLS, NOCOUNT ON
SET NUMERIC_ROUNDABORT, IMPLICIT_TRANSACTIONS, XACT_ABORT OFF
GO

INSERT TFEcommerce.mapun.BRATES(BRATE_ID, TITLE, REMARKS, DESCRIPTION, RATE, DATE_CREATED, CREATED_BY, DATE_UPDATED, UPDATED_BY, IS_ACTIVE) VALUES ('f875d3d9-6e5a-ed11-819a-000d3a806f52', N'Provincial', NULL, N'Base Property Tax Rate for assessed properties within provincial areas', 1.00, '2022-11-02 05:26:07.4219417', '38d1423e-f36b-1410-8502-0086aea93fd9', '2022-11-02 19:13:01.7645015', '38d1423e-f36b-1410-8502-0086aea93fd9', CONVERT(bit, 'True'))
INSERT TFEcommerce.mapun.BRATES(BRATE_ID, TITLE, REMARKS, DESCRIPTION, RATE, DATE_CREATED, CREATED_BY, DATE_UPDATED, UPDATED_BY, IS_ACTIVE) VALUES ('8fa77494-7232-ed11-b495-000d3a80f777', N'Municipal', NULL, N'Base Property Tax Rate for assessed properties within municipal areas', 2.00, NULL, NULL, '2022-11-02 19:13:16.3143940', '38d1423e-f36b-1410-8502-0086aea93fd9', CONVERT(bit, 'True'))
GO